### ISSUE TITLE
None of the HPO terms in the example is valid?

### ISSUE THREAD

**Issue by hernanmd** [WGLab/Phen2Gene#9]
Hi, just doing a first pass here, but none of the HPO terms in the example is recognized as valid:

$ ./phen2gene.py -v -m HP:0000001 HP:0000021 HP:0000027 HP:0030905 HP:0030910 HP:0010628 -out out/out

HPO weighting model: Ontology-based Informatin Content

HP:0000001 is not a valid human phenotype.
Phen2Gene skipped it.
HP:0030910 is not a valid human phenotype.
Phen2Gene skipped it.
HP:0000021 is not a valid HPO term. cal
HP:0000027 is not a valid HPO term. cal
HP:0030905 is not a valid HPO term. cal
HP:0010628 is not a valid HPO term. cal
Finished.
Output path: out/out/

Didn't checked the source code yet, but any hints?

My environment

Python 3.7.3
anaconda Command line client (version 1.7.2)
Linux

**Comment by MenggeZhao** [comment]
This sample is outdated. HP:0030910 is obsolete in the latest HPO version and skipped by Phen2Gene. HP:0000001 has no real clinical meaning, new Phen2Gene version also skips it. For the other HPO, I fixed a small bug, and now it works for manual input.

**Comment by kyauy** [comment]
Hi, I still have this same bug. I just git clone your repository.
I use the conda environnement you recommand. 

I use this command : 
$ python phen2gene.py -m HP:0003558 HP:0006895 HP:0002020 HP:0001263 HP:0002385 HP:0003487 HP:0004897 -out test -w sk -v

HPO weighting model: Skewness

HP:0003558 is not a valid human phenotype.
Phen2Gene skipped it.
HP:0006895 is not a valid human phenotype.
Phen2Gene skipped it.
HP:0002020 is not a valid human phenotype.
Phen2Gene skipped it.
HP:0001263 is not a valid human phenotype.
Phen2Gene skipped it.
HP:0002385 is not a valid human phenotype.
Phen2Gene skipped it.
HP:0003487 is not a valid human phenotype.
Phen2Gene skipped it.
HP:0004897 is not a valid human phenotype.
Phen2Gene skipped it.
Finished.
Output path: test/

Any ideas why ?
Thanks!

**Comment by jimhavrilla** [comment]
@MenggeZhao can you handle this please? Also to the user, are these outdated terms? And have you tried using the file input argument just in case?

**Comment by MenggeZhao** [comment]
Hi Kevin,

Your command worked in my environment. Here is a portion of the results for
your command.

Rank    Gene    ID      Score   Status
1       ATRX    546     1.0     SeedGene
2       SDHA    6389    0.575879        SeedGene
3       SDHD    6392    0.569619        SeedGene
4       SDHAF1  644096  0.524051        SeedGene
5       CACNA1S 779     0.501502        SeedGene
6       RYR1    6261    0.483659        SeedGene
7       ABCD1   215     0.431775        SeedGene
8       FA2H    79152   0.296679        SeedGene
9       NADK2   133686  0.284115        SeedGene

My guess is that you did not install the Knowledgebase. Just check if you
have the folder: Phen2Gene/lib/Knowledgebase. If you don't have it, run ' bash
getKB.sh '. Then run your command again to see if you got a result.

Thanks,
Mengge

**Comment by jimhavrilla** [comment]
@kyauy did this resolve your problem?

**Comment by kyauy** [comment]
Yes, thanks! I see that you added this info to the README, so that's great :)

**Comment by jimhavrilla** [comment]
Great thanks for pointing it out. Now it should be clearer
